export enum PoliticalPreferenceEnum {
    PRO_EUROPEAN_INTEGRATION = 'pro-european-integration',
    PRO_RUSSIAN_ORIENTATION = 'pro-russian-orientation',
    PRO_NATO_ORIENTATION = 'pro-nato-orientation',
    PRO_USA_ORIENTATION = 'pro-usa-orientation',
    PRO_CHINA_ORIENTATION = 'pro-china-orientation',
    PRO_UCRANIAN_ORIENTATION = 'pro-ucranian-orientation',
    PRO_TRANSNISTRIAN_ORIENTATION = 'pro-transnistrian-orientation',
    SOCIAL_DEMOCRAT = 'social-democrat',
    CONSERVATIVE = 'conservative',
    LIBERAL = 'liberal',
    LIBERAL_DEMOCRAT = 'liberal-democrat',
    SOCIALIST = 'socialist',
    COMMUNIST = 'communist',
    AGRARIAN = 'agrarian',
    GREEN = 'green',
    INDEPENDENT = 'independent',
    NON_PARTISAN = 'non-partisan',
    REGIONAL = 'regional',
    ANARCHIST = 'anarchist',
}
